import { MetadataRoute } from 'next'

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'Satvik Chachra - Software Engineer',
    short_name: 'Satvik',
    description: 'Portfolio of Satvik Chachra, a software engineer specializing in AI and modern web technologies.',
    start_url: '/',
    display: 'standalone',
    background_color: '#000000',
    theme_color: '#000000',
    icons: [
      {
        src: '/icon.svg',
        sizes: 'any',
        type: 'image/svg+xml',
      },
      {
        src: '/apple-icon.png', // Automatically generated by Next.js from apple-icon.tsx
        sizes: '180x180',
        type: 'image/png',
      }
    ],
  }
}
