import type { MetadataRoute } from 'next';
import { getAllPosts } from '@/lib/blog';
import { BASE_URL } from '@/lib/metadata';

// Emitted as a static file by `next build` itself, so it ships in `out/`
// regardless of how the host invokes the build. (Previously generated by
// next-sitemap's `postbuild` hook, which the static host never ran — so
// /sitemap.xml 404'd in production.)
export const dynamic = 'force-static';

const STATIC_PATHS = ['', '/about', '/projects', '/blog', '/contact'] as const;

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date();

  const staticPages: MetadataRoute.Sitemap = STATIC_PATHS.map((path) => ({
    url: `${BASE_URL}${path}`,
    lastModified: now,
    changeFrequency: 'weekly',
    priority: path === '' ? 1 : 0.8,
  }));

  const blogPosts: MetadataRoute.Sitemap = getAllPosts().map((post) => ({
    url: `${BASE_URL}/blog/${post.slug}`,
    lastModified: new Date(post.date),
    changeFrequency: 'monthly',
    priority: 0.6,
  }));

  return [...staticPages, ...blogPosts];
}
